{% set rel_recipe = "conda.recipe" %}
{% set name = "btax" %}
{% set git_org = "PeterDSteinberg" %}
{% set source_url = "https://github.com/PeterDSteinberg/B-Tax/archive/0.1.096.tar.gz" %}
{% set version = "0.1.096" %}
{% set sha256 = "ba6f4a123f4cd2a7dfb2e161e469a1c4dc75e75fc1305f9f55b2feceef09a583" %}
{% set repo_name = "B-Tax" %}


package:

  name: {{ name }}

  version: {{ version }}



source:

  url: {{ source_url }}

  sha256: {{ sha256 }}



build:

  number: 0

  script: python setup.py install --single-version-externally-managed --record record.txt



requirements:

  build:

    - setuptools

    - python 2.7.10



  run:

    - setuptools

    - scipy

    - taxcalc

    - matplotlib

    - numpy

    - pandas ==0.18.1

    - python 2.7.10

    - pytest

    - xlrd



about:

  home: https://github.com/open-source-economics/B-Tax/

  summary: B-Tax is a model used to evaluate the effect of taxation on investment incentives.



extra:

  recipe-maintainers:

   - Jason Debacker

   - Peter Steinberg

   - TJ Alumbaugh


