{% set rel_recipe = "conda.recipe" %}
{% set sha256 = "920ee3a1852082d11e08529111287d498144827d2865e06370c00a50dfffc755" %}
{% set name = "btax" %}
{% set repo_name = "B-Tax" %}
{% set git_org = "PeterDSteinberg" %}
{% set version = "0.1.095" %}
{% set source_url = "https://github.com/PeterDSteinberg/B-Tax/archive/0.1.095.tar.gz" %}


package:

  name: {{ name }}

  version: {{ version }}



source:

  url: {{ source_url }}

  sha256: {{ sha256 }}



build:

  number: 0

  script: python setup.py install --single-version-externally-managed --record record.txt



requirements:

  build:

    - setuptools

    - python 2.7.10



  run:

    - setuptools

    - scipy

    - taxcalc

    - matplotlib

    - numpy

    - pandas >=0.18.0

    - python 2.7.10

    - pytest

    - xlrd



about:

  home: https://github.com/open-source-economics/B-Tax/

  summary: B-Tax is a model used to evaluate the effect of taxation on investment incentives.



extra:

  recipe-maintainers:

   - Jason Debacker

   - Peter Steinberg

   - TJ Alumbaugh


