{% set rel_recipe = "conda.recipe" %}
{% set sha256 = "13413bc9c63c24c5702d2b9593a317bbd4381770d01b90a66149a2bd04dccb9d" %}
{% set name = "taxcalc" %}
{% set repo_name = "Tax-Calculator" %}
{% set git_org = "PeterDSteinberg" %}
{% set version = "0.6.593" %}
{% set source_url = "https://github.com/PeterDSteinberg/Tax-Calculator/archive/0.6.593.tar.gz" %}
package:

  name: {{ name }}

  version: {{ version }}



source:

  url: {{ source_url }}

  sha256: {{ sha256 }}



build:

  number: 0

  script: python setup.py install --single-version-externally-managed --record record.txt



requirements:

  build:

    - pytest

    - setuptools

    - python

    - numpy ==1.11

    - pandas >=0.18.0

    - numba

    - toolz

    - six

  run:

    - pytest

    - setuptools

    - python

    - numpy ==1.11

    - pandas >=0.18.0

    - numba

    - toolz

    - six



about:

  home: http://www.github.com/OpenSourcePolicyCenter

  summary: Federal Individual Income Tax Microsimulation Model



extra:

  recipe-maintainers:

   - Peter Steinberg

   - TJ Alumbaugh
