{% set rel_recipe = "conda.recipe" %}
{% set name = "taxcalc" %}
{% set git_org = "PeterDSteinberg" %}
{% set source_url = "https://github.com/PeterDSteinberg/Tax-Calculator/archive/0.6.594.tar.gz" %}
{% set version = "0.6.594" %}
{% set sha256 = "3e20f1b1ae0fd935133dd1f183604a30419f22cc97da1090037237ab15fa3635" %}
{% set repo_name = "Tax-Calculator" %}
package:

  name: {{ name }}

  version: {{ version }}



source:

  url: {{ source_url }}

  sha256: {{ sha256 }}



build:

  number: 0

  script: python setup.py install --single-version-externally-managed --record record.txt



requirements:

  build:

    - pytest

    - setuptools

    - python

    - numpy ==1.11

    - pandas ==0.18.1

    - numba

    - toolz

    - six

  run:

    - pytest

    - setuptools

    - python

    - numpy ==1.11

    - pandas ==0.18.1

    - numba

    - toolz

    - six



about:

  home: http://www.github.com/OpenSourcePolicyCenter

  summary: Federal Individual Income Tax Microsimulation Model



extra:

  recipe-maintainers:

   - Peter Steinberg

   - TJ Alumbaugh
