{% set taxcalc_version = "0.7.2" %}
{% set git_org = "PeterDSteinberg" %}
{% set repo_name = "Tax-Calculator" %}
{% set name = "taxcalc" %}
{% set rel_recipe = "conda.recipe" %}
{% set source_url = "https://github.com/PeterDSteinberg/Tax-Calculator/archive/0.7.2.tar.gz" %}
{% set sha256 = "28e7167b57e99b9ddf0bb530fdd5cf452059766278141e7b4b16219d6977b327" %}
{% set version = "0.7.2" %}
package:
  name: taxcalc
  version: 0.4

requirements:
  build:
    - pytest
    - setuptools
    - python
    - numpy ==1.10.4
    - pandas <=0.18.0
    - numba
    - toolz
    - six
  run:
    - pytest
    - setuptools
    - python
    - numpy ==1.10.4
    - pandas <=0.18.0
    - numba
    - toolz
    - six

about:
  home: http://www.github.com/OpenSourcePolicyCenter
