{% set repo_name = "Tax-Calculator" %}
{% set rel_recipe = "conda.recipe" %}
{% set sha256 = "bfbf4765c66ba56963a6d38ae82956afb2c348805a7df9bcacbcdecedb218d8d" %}
{% set source_url = "https://github.com/PeterDSteinberg/Tax-Calculator/archive/0.6.59.tar.gz" %}
{% set git_org = "PeterDSteinberg" %}
{% set name = "taxcalc" %}
{% set version = "0.6.59" %}
package:

  name: {{ name }}

  version: {{ version }}



source:

  url: {{ source_url }}

  sha256: {{ sha256 }}



requirements:

  build:

    - pytest

    - setuptools

    - python

    - numpy ==1.10.4

    - pandas >=0.18.0

    - numba

    - toolz

    - six

  run:

    - pytest

    - setuptools

    - python

    - numpy ==1.10.4

    - pandas >=0.18.0

    - numba

    - toolz

    - six



about:

  home: http://www.github.com/OpenSourcePolicyCenter

  summary: Federal Individual Income Tax Microsimulation Model



extra:

  recipe-maintainers:

   - Peter Steinberg

   - TJ Alumbaugh
