{% set rel_recipe = "Python/conda.recipe" %}
{% set name = "ogusa" %}
{% set git_org = "PeterDSteinberg" %}
{% set taxcalc_version = "0.6.594" %}
{% set source_url = "https://github.com/PeterDSteinberg/OG-USA/archive/0.5.4991.tar.gz" %}
{% set version = "0.5.4991" %}
{% set sha256 = "865d7ca24cad87e0581efdae4c4a50255ee0a701792e4ad31752ede8cb7bd43c" %}
{% set repo_name = "OG-USA" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ source_url }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - setuptools
    - scipy
    - matplotlib
    - numpy
    - pandas ==0.18.1
    - pytest
    - python 2.7*

  run:
    - setuptools
    - scipy
    - taxcalc =={{ taxcalc_version }}
    - matplotlib
    - numpy
    - pandas ==0.18.1
    - pytest
    - python 2.7*

about:
  home: https://github.com/open-source-economics/OG-USA/
  summary: Dynamic Tax Scoring Model

extra:
  recipe-maintainers:
   - Peter Steinberg
   - TJ Alumbaugh
