{% set repo_name = "OG-USA" %}
{% set rel_recipe = "Python/conda.recipe" %}
{% set sha256 = "b6e0b3d1f037ddfce4e0a6675133c5ea7565275728f677e45e5841d9d0b33ba7" %}
{% set source_url = "https://github.com/PeterDSteinberg/OG-USA/archive/0.5.49.tar.gz" %}
{% set git_org = "PeterDSteinberg" %}
{% set name = "ogusa" %}
{% set version = "0.5.49" %}
package:

  name: {{ name }}

  version: {{ version }}



source:

  url: {{ source_url }}

  sha256: {{ sha256 }}



requirements:

  build:

    - setuptools

    - scipy

    - matplotlib

    - numpy

    - pandas >=0.18.0

    - pytest

    - python 2.7.10



  run:

    - setuptools

    - scipy

    - taxcalc

    - matplotlib

    - numpy

    - pandas >=0.18.0

    - pytest

    - python 2.7.10



about:

  home: https://github.com/open-source-economics/OG-USA/

  summary: Dynamic Tax Scoring Model



extra:

  recipe-maintainers:

   - Peter Steinberg

   - TJ Alumbaugh
