{% set sha256 = "b3bdfa5b41da6da661c97241fbce60d1f9b2a3c976de5c432788d56054a16dbc" %}
{% set source_url = "https://github.com/PeterDSteinberg/OG-USA/archive/0.5.492.tar.gz" %}
{% set rel_recipe = "Python/conda.recipe" %}
{% set name = "ogusa" %}
{% set version = "0.5.492" %}
{% set git_org = "PeterDSteinberg" %}
{% set repo_name = "OG-USA" %}
package:

  name: {{ name }}

  version: {{ version }}



source:

  url: {{ source_url }}

  sha256: {{ sha256 }}



build:

  number: 0

  script: python setup.py install --single-version-externally-managed --record record.txt



requirements:

  build:

    - setuptools

    - scipy

    - matplotlib

    - numpy

    - pandas >=0.18.0

    - pytest

    - python 2.7.10



  run:

    - setuptools

    - scipy

    - taxcalc

    - matplotlib

    - numpy

    - pandas >=0.18.0

    - pytest

    - python 2.7.10



about:

  home: https://github.com/open-source-economics/OG-USA/

  summary: Dynamic Tax Scoring Model



extra:

  recipe-maintainers:

   - Peter Steinberg

   - TJ Alumbaugh
