{% set rel_recipe = "Python/conda.recipe" %}
{% set name = "ogusa" %}
{% set git_org = "PeterDSteinberg" %}
{% set source_url = "https://github.com/PeterDSteinberg/OG-USA/archive/0.5.494.tar.gz" %}
{% set version = "0.5.494" %}
{% set sha256 = "cb8ca8a523d2483464d797e96729b83f71a59804ac23c0aa813180f70942c837" %}
{% set repo_name = "OG-USA" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ source_url }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - setuptools
    - scipy
    - matplotlib
    - numpy
    - pandas ==0.18.1
    - pytest
    - python 2.7.10

  run:
    - setuptools
    - scipy
    - taxcalc
    - matplotlib
    - numpy
    - pandas ==0.18.1
    - pytest
    - python 2.7

about:
  home: https://github.com/open-source-economics/OG-USA/
  summary: Dynamic Tax Scoring Model

extra:
  recipe-maintainers:
   - Peter Steinberg
   - TJ Alumbaugh
