{% set rel_recipe = "Python/conda.recipe" %}
{% set name = "ogusa" %}
{% set git_org = "PeterDSteinberg" %}
{% set source_url = "https://github.com/PeterDSteinberg/OG-USA/archive/0.5.496.tar.gz" %}
{% set version = "0.5.496" %}
{% set sha256 = "6557cd5f07cad09e99fe2462de7ceae6a3839b78ceca3daa97ed723d422007b1" %}
{% set repo_name = "OG-USA" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ source_url }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - setuptools
    - scipy
    - matplotlib
    - numpy
    - pandas ==0.18.1
    - pytest
    - python ==2.7*

  run:
    - setuptools
    - scipy
    - taxcalc
    - matplotlib
    - numpy
    - pandas ==0.18.1
    - pytest
    - python ==2.7*

about:
  home: https://github.com/open-source-economics/OG-USA/
  summary: Dynamic Tax Scoring Model

extra:
  recipe-maintainers:
   - Peter Steinberg
   - TJ Alumbaugh
